package com.design.managedebts.model.group;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "group_user_info")
public class GroupUserInfo {

    // TODO : make composite key from userId and groupId , remove autogenerated-> waste of space.

    @Id
    private long id;

    // index on this too
    private long userId;

    private long groupId; // serach has to be usually done by group id also, need of index

    public GroupUserInfo() {
    }

    public GroupUserInfo(long id, long userId, long groupId) {
        this.id = id;
        this.userId = userId;
        this.groupId = groupId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public long getGroupId() {
        return groupId;
    }

    public void setGroupId(long groupId) {
        this.groupId = groupId;
    }

    @Override
    public String toString() {
        return "GroupUserInfo{" +
                "id=" + id +
                ", userId=" + userId +
                ", groupId=" + groupId +
                '}';
    }
}
